/* Habitat — trade categories, terminology dictionaries, and task translation.
 *
 * Each trade has an icon, color, and display name. The terminology maps
 * translate common homeowner phrases into the specific language a trade
 * worker needs to hear. translateTaskForTrade() rewrites a task's title
 * and description using the trade's dictionary.
 */
"use strict";

/* ------------------------------------------------------- trade categories */
export const TRADES = [
  { id: "plumbing", icon: "🔧", color: "#6ee7ff", name: "Plumbing" },
  { id: "electrical", icon: "⚡", color: "#f5c451", name: "Electrical" },
  { id: "landscaping", icon: "🌿", color: "#34d399", name: "Landscaping" },
  { id: "hvac", icon: "❄️", color: "#a78bfa", name: "HVAC" },
  { id: "roofing", icon: "🏠", color: "#fb923c", name: "Roofing" },
  { id: "general", icon: "🔨", color: "#94b4a4", name: "General" },
];

export function tradeById(id) {
  return TRADES.find((t) => t.id === id) || null;
}

export function tradeColor(id) {
  const t = tradeById(id);
  return t ? t.color : "#94b4a4";
}

export function tradeName(id) {
  const t = tradeById(id);
  return t ? t.name : "General";
}

export function tradeIcon(id) {
  const t = tradeById(id);
  return t ? t.icon : "🔨";
}

/* ------------------------------------------------- terminology dictionaries */
/*
 * Each entry maps a homeowner phrase (lowercase) to the trade-specific
 * language a worker needs to hear. The translate function does a
 * case-insensitive substring match and replaces the matched portion.
 */
const TERMINOLOGY = {
  plumbing: [
    { home: "water won't stop running", trade: "replace valve stem / cartridge" },
    { home: "water wont stop running", trade: "replace valve stem / cartridge" },
    { home: "toilet keeps running", trade: "replace flapper / fill valve" },
    { home: "toilet wont flush", trade: "check flush valve / wax ring" },
    { home: "no hot water", trade: "check heating element / thermostat / anode rod" },
    { home: "sink is clogged", trade: "clear drain blockage / check P-trap" },
    { home: "sink wont drain", trade: "clear drain blockage / check P-trap" },
    { home: "low water pressure", trade: "check PRV (40-60 PSI) / aerator / pipe corrosion" },
    { home: "leaking pipe", trade: "locate and repair pipe joint / fitting" },
    { home: "leak under sink", trade: "inspect supply lines / drain connections / P-trap" },
    { home: "water heater", trade: "inspect water heater / anode rod / T&P valve" },
    { home: "water heater making noise", trade: "flush tank sediment / check anode rod" },
    { home: "sewer smell", trade: "check P-trap water seal / vent stack" },
    { home: "water is discolored", trade: "flush system / check anode rod / pipe corrosion" },
    { home: "shower pressure is bad", trade: "replace shower valve cartridge / clean head" },
    { home: "pipe is frozen", trade: "thaw with hair dryer / heating pad — NEVER open flame" },
    { home: "sewage backup", trade: "main sewer line blockage — call professional immediately" },
    { home: "drip", trade: "replace washer / O-ring" },
    { home: "faucet", trade: "replace cartridge / valve seat" },
    { home: "shower", trade: "check shower valve / head / cartridge" },
    { home: "drain", trade: "clear blockage / inspect vent stack" },
    { home: "pipe", trade: "inspect pipe run / fittings" },
    { home: "water", trade: "check water line / pressure" },
    { home: "toilet", trade: "inspect flapper / fill valve / flush valve / wax ring" },
    { home: "valve", trade: "replace valve / cartridge / stem" },
    { home: "p-trap", trade: "inspect P-trap / clean / reseal" },
    { home: "backflow", trade: "test backflow preventer / check valve" },
    { home: "vent stack", trade: "inspect vent stack / clear blockage" },
    { home: "supply line", trade: "inspect supply line / connections" },
    { home: "hose bib", trade: "inspect hose bib / outdoor faucet" },
    { home: "sprinkler", trade: "inspect irrigation system / emitters" },
    { home: "water pressure", trade: "check PRV / aerator / pipe condition" },
    { home: "clog", trade: "clear blockage / snake drain" },
    { home: "overflow", trade: "check fill valve / float height" },
    { home: "running toilet", trade: "replace flapper / adjust fill valve" },
    { home: "slow drain", trade: "clear blockage / snake drain / check vent" },
    { home: "burst pipe", trade: "shut off main valve / replace damaged section" },
    { home: "main water line", trade: "inspect main service line / shutoff valve" },
    { home: "well pump", trade: "inspect well pump / pressure tank" },
    { home: "sump pump", trade: "test sump pump / check discharge line" },
    { home: "garbage disposal", trade: "inspect disposal / reset / replace" },
    { home: "dishwasher leak", trade: "inspect dishwasher supply / drain connection" },
    { home: "washing machine leak", trade: "inspect washer hoses / connections" },
    { home: "bathtub", trade: "inspect tub drain / overflow / spout" },
    { home: "sink", trade: "inspect sink drain / supply / faucet" },
    { home: "water meter", trade: "inspect water meter / main shutoff" },
    { home: "pressure regulator", trade: "test / replace PRV" },
    { home: "anode rod", trade: "inspect / replace anode rod" },
    { home: "t&p valve", trade: "test T&P relief valve" },
    { home: "water softener", trade: "inspect water softener / regenerate" },
    { home: "sump", trade: "inspect sump pump / pit" },
    { home: "sewer line", trade: "inspect sewer line / cleanout" },
    { home: "cleanout", trade: "access cleanout / clear blockage" },
    { home: "trap", trade: "inspect trap / water seal" },
    { home: "fitting", trade: "inspect fitting / joint / connection" },
    { home: "joint", trade: "inspect joint / fitting / seal" },
    { home: "corrosion", trade: "inspect corrosion / replace affected section" },
    { home: "rust", trade: "inspect corrosion / replace affected section" },
    { home: "mold", trade: "address moisture source / remediate mold" },
    { home: "water damage", trade: "locate source / repair / assess damage" },
    { home: "flood", trade: "shut off water / assess damage / repair" },
    { home: "freeze", trade: "thaw pipe / insulate / prevent freezing" },
    { home: "insulation", trade: "insulate pipes / check for freezing risk" },
    { home: "renovation", trade: "rough-in plumbing / relocate lines" },
    { home: "remodel", trade: "rough-in plumbing / relocate lines" },
    { home: "new construction", trade: "install water supply / drain / vent" },
    { home: "permit", trade: "verify plumbing permit / inspection" },
    { home: "inspection", trade: "schedule plumbing inspection" },
    { home: "code", trade: "verify code compliance" },
    { home: "leak detection", trade: "perform leak detection / pressure test" },
    { home: "pressure test", trade: "perform pressure test" },
    { home: "camera inspection", trade: "perform sewer camera inspection" },
    { home: "jet", trade: "hydro-jet drain line" },
    { home: "snake", trade: "snake drain line" },
    { home: "plunge", trade: "plunge drain" },
    { home: "auger", trade: "use drain auger" },
    { home: "rooter", trade: "use drain rooter" },
    { home: "excavation", trade: "excavate for pipe repair" },
    { home: "trench", trade: "dig trench for pipe" },
    { home: "bore", trade: "bore under obstacle" },
    { home: "tunnel", trade: "tunnel for pipe access" },
    { home: "slab leak", trade: "locate slab leak / reroute or repair" },
    { home: "pinhole leak", trade: "locate pinhole leak / replace section" },
    { home: "polybutylene", trade: "replace polybutylene piping" },
    { home: "galvanized", trade: "replace galvanized piping" },
    { home: "copper", trade: "inspect / repair copper piping" },
    { home: "pex", trade: "inspect / repair PEX piping" },
    { home: "pvc", trade: "inspect / repair PVC piping" },
    { home: "cpvc", trade: "inspect / repair CPVC piping" },
    { home: "abs", trade: "inspect / repair ABS piping" },
    { home: "cast iron", trade: "inspect / repair cast iron piping" },
    { home: "lead", trade: "test for lead / replace lead piping" },
    { home: "gas line", trade: "inspect gas line / test for leaks" },
    { home: "gas leak", trade: "EMERGENCY: shut off gas / evacuate / call utility" },
    { home: "water main", trade: "inspect water main / service line" },
    { home: "service line", trade: "inspect service line / main" },
    { home: "shutoff", trade: "locate / test shutoff valve" },
    { home: "shut-off", trade: "locate / test shutoff valve" },
    { home: "main valve", trade: "locate / test main shutoff valve" },
    { home: "angle stop", trade: "inspect / replace angle stop" },
    { home: "straight stop", trade: "inspect / replace straight stop" },
    { home: "gate valve", trade: "inspect / replace gate valve" },
    { home: "ball valve", trade: "inspect / replace ball valve" },
    { home: "globe valve", trade: "inspect / replace globe valve" },
    { home: "check valve", trade: "inspect / replace check valve" },
    { home: "mixing valve", trade: "inspect / replace mixing valve" },
    { home: "thermostatic valve", trade: "inspect / replace thermostatic valve" },
    { home: "pressure balance valve", trade: "inspect / replace pressure balance valve" },
    { home: "expansion tank", trade: "inspect / replace expansion tank" },
    { home: "water hammer", trade: "install water hammer arrestor" },
    { home: "arrestor", trade: "install water hammer arrestor" },
    { home: "air gap", trade: "inspect / install air gap" },
    { home: "vacuum breaker", trade: "inspect / install vacuum breaker" },
    { home: "backwater valve", trade: "inspect / install backwater valve" },
    { home: "grease trap", trade: "inspect / clean grease trap" },
    { home: "interceptor", trade: "inspect / clean interceptor" },
    { home: "catch basin", trade: "inspect / clean catch basin" },
    { home: "floor drain", trade: "inspect / clean floor drain" },
    { home: "trench drain", trade: "inspect / clean trench drain" },
    { home: "downspout", trade: "inspect / repair downspout" },
    { home: "leader", trade: "inspect / repair leader" },
    { home: "storm drain", trade: "inspect / clear storm drain" },
    { home: "sanitary drain", trade: "inspect / clear sanitary drain" },
    { home: "waste line", trade: "inspect / repair waste line" },
    { home: "vent", trade: "inspect vent / vent stack" },
    { home: "stack", trade: "inspect stack / vent" },
    { home: "soil pipe", trade: "inspect / repair soil pipe" },
    { home: "waste pipe", trade: "inspect / repair waste pipe" },
    { home: "drain pipe", trade: "inspect / repair drain pipe" },
    { home: "water pipe", trade: "inspect / repair water pipe" },
    { home: "supply pipe", trade: "inspect / repair supply pipe" },
    { home: "distribution", trade: "inspect water distribution system" },
    { home: "manifold", trade: "inspect manifold / distribution" },
    { home: "zone valve", trade: "inspect / replace zone valve" },
    { home: "radiant", trade: "inspect radiant heating system" },
    { home: "hydronic", trade: "inspect hydronic system" },
    { home: "boiler", trade: "inspect boiler / heat exchanger" },
    { home: "furnace", trade: "inspect furnace / heat exchanger" },
    { home: "baseboard", trade: "inspect baseboard heat" },
    { home: "radiator", trade: "inspect radiator / valve" },
    { home: "thermostat", trade: "inspect / replace thermostat" },
    { home: "zone", trade: "inspect zone / damper" },
    { home: "damper", trade: "inspect / adjust damper" },
    { home: "duct", trade: "inspect ductwork / seals" },
    { home: "register", trade: "inspect / adjust register" },
    { home: "grille", trade: "inspect / clean grille" },
    { home: "return", trade: "inspect return air" },
    { home: "supply", trade: "inspect supply air" },
    { home: "airflow", trade: "check airflow / balance" },
    { home: "balance", trade: "balance airflow" },
    { home: "static pressure", trade: "measure static pressure" },
    { home: "cfm", trade: "measure CFM" },
    { home: "tonnage", trade: "verify tonnage / capacity" },
    { home: "seer", trade: "verify SEER rating" },
    { home: "hspf", trade: "verify HSPF rating" },
    { home: "afue", trade: "verify AFUE rating" },
    { home: "eer", trade: "verify EER rating" },
    { home: "refrigerant", trade: "check refrigerant level / type" },
    { home: "freon", trade: "check R-22 / refrigerant level" },
    { home: "r-410a", trade: "check R-410A / refrigerant level" },
    { home: "r-22", trade: "check R-22 / refrigerant level" },
    { home: "r-32", trade: "check R-32 / refrigerant level" },
    { home: "r-454b", trade: "check R-454B / refrigerant level" },
    { home: "compressor", trade: "inspect compressor / windings" },
    { home: "condenser", trade: "inspect condenser coil / fan" },
    { home: "evaporator", trade: "inspect evaporator coil" },
    { home: "coil", trade: "inspect / clean coil" },
    { home: "blower", trade: "inspect blower motor / wheel" },
    { home: "motor", trade: "inspect motor / capacitor" },
    { home: "capacitor", trade: "test / replace capacitor" },
    { home: "contactor", trade: "inspect / replace contactor" },
    { home: "relay", trade: "inspect / replace relay" },
    { home: "transformer", trade: "test / replace transformer" },
    { home: "control board", trade: "inspect / replace control board" },
    { home: "circuit board", trade: "inspect / replace circuit board" },
    { home: "ignitor", trade: "inspect / replace ignitor" },
    { home: "flame sensor", trade: "clean / replace flame sensor" },
    { home: "thermocouple", trade: "inspect / replace thermocouple" },
    { home: "thermopile", trade: "inspect / replace thermopile" },
    { home: "gas valve", trade: "inspect / replace gas valve" },
    { home: "burner", trade: "inspect / clean burner" },
    { home: "heat exchanger", trade: "inspect heat exchanger / cracks" },
    { home: "inducer", trade: "inspect inducer motor" },
    { home: "draft", trade: "check draft / venting" },
    { home: "venting", trade: "inspect venting / flue" },
    { home: "flue", trade: "inspect flue / venting" },
    { home: "chimney", trade: "inspect chimney / cap" },
    { home: "b vent", trade: "inspect B vent" },
    { home: "direct vent", trade: "inspect direct vent" },
    { home: "power vent", trade: "inspect power vent" },
    { home: "condensate", trade: "inspect condensate drain / pump" },
    { home: "drain pan", trade: "inspect drain pan / float switch" },
    { home: "float switch", trade: "test / replace float switch" },
    { home: "safety switch", trade: "test safety switch" },
    { home: "limit switch", trade: "test / replace limit switch" },
    { home: "pressure switch", trade: "test / replace pressure switch" },
    { home: "rollout switch", trade: "test / replace rollout switch" },
    { home: "high limit", trade: "test high limit switch" },
    { home: "low limit", trade: "test low limit switch" },
    { home: "aquastat", trade: "inspect / replace aquastat" },
    { home: "circulator", trade: "inspect circulator pump" },
    { home: "pump", trade: "inspect pump / motor" },
    { home: "zone pump", trade: "inspect zone pump" },
    { home: "system pump", trade: "inspect system pump" },
    { home: "booster pump", trade: "inspect booster pump" },
    { home: "sewage pump", trade: "inspect sewage pump" },
    { home: "effluent pump", trade: "inspect effluent pump" },
    { home: "grinder pump", trade: "inspect grinder pump" },
    { home: "condensate pump", trade: "inspect condensate pump" },
    { home: "drain pump", trade: "inspect drain pump" },
    { home: "transfer pump", trade: "inspect transfer pump" },
    { home: "recirculation pump", trade: "inspect recirculation pump" },
    { home: "hot water recirculation", trade: "inspect recirculation system" },
    { home: "instant hot water", trade: "install recirculation system" },
    { home: "tankless", trade: "inspect tankless water heater" },
    { home: "tankless water heater", trade: "inspect / service tankless unit" },
    { home: "on-demand", trade: "inspect on-demand water heater" },
    { home: "point of use", trade: "inspect point-of-use heater" },
    { home: "booster heater", trade: "inspect booster heater" },
    { home: "heat pump water heater", trade: "inspect heat pump water heater" },
    { home: "solar water heater", trade: "inspect solar water heater" },
    { home: "indirect water heater", trade: "inspect indirect water heater" },
    { home: "storage water heater", trade: "inspect storage water heater" },
    { home: "commercial water heater", trade: "inspect commercial water heater" },
    { home: "residential water heater", trade: "inspect residential water heater" },
    { home: "gas water heater", trade: "inspect gas water heater" },
    { home: "electric water heater", trade: "inspect electric water heater" },
    { home: "oil water heater", trade: "inspect oil water heater" },
    { home: "propane water heater", trade: "inspect propane water heater" },
    { home: "natural gas", trade: "inspect natural gas line / connections" },
    { home: "lp gas", trade: "inspect LP gas line / connections" },
    { home: "propane", trade: "inspect propane line / connections" },
    { home: "butane", trade: "inspect butane line / connections" },
    { home: "fuel oil", trade: "inspect fuel oil line / connections" },
    { home: "oil tank", trade: "inspect oil tank / lines" },
    { home: "gas meter", trade: "inspect gas meter / connections" },
    { home: "gas regulator", trade: "inspect / replace gas regulator" },
    { home: "gas shutoff", trade: "locate / test gas shutoff" },
    { home: "gas valve", trade: "inspect / replace gas valve" },
    { home: "gas connector", trade: "inspect gas connector" },
    { home: "flex connector", trade: "inspect flex connector" },
    { home: "csst", trade: "inspect CSST / bonding" },
    { home: "bonding", trade: "verify electrical bonding" },
    { home: "grounding", trade: "verify grounding" },
    { home: "earth ground", trade: "inspect earth ground" },
    { home: "ground rod", trade: "inspect ground rod" },
    { home: "ground wire", trade: "inspect ground wire" },
    { home: "water heater pan", trade: "inspect water heater pan / drain" },
    { home: "drain valve", trade: "inspect / replace drain valve" },
    { home: "element", trade: "inspect / replace heating element" },
    { home: "dip tube", trade: "inspect / replace dip tube" },
    { home: "cold water inlet", trade: "inspect cold water inlet" },
    { home: "hot water outlet", trade: "inspect hot water outlet" },
    { home: "baffle", trade: "inspect baffle" },
    { home: "flue baffle", trade: "inspect flue baffle" },
    { home: "draft hood", trade: "inspect draft hood" },
    { home: "heat trap", trade: "inspect heat trap" },
    { home: "nipple", trade: "inspect nipple / fitting" },
    { home: "dielectric", trade: "inspect dielectric union" },
    { home: "union", trade: "inspect union / fitting" },
    { home: "coupling", trade: "inspect coupling / fitting" },
    { home: "adapter", trade: "inspect adapter / fitting" },
    { home: "bushing", trade: "inspect bushing / fitting" },
    { home: "reducer", trade: "inspect reducer / fitting" },
    { home: "elbow", trade: "inspect elbow / fitting" },
    { home: "tee", trade: "inspect tee / fitting" },
    { home: "wye", trade: "inspect wye / fitting" },
    { home: "cross", trade: "inspect cross / fitting" },
    { home: "cap", trade: "inspect cap / fitting" },
    { home: "plug", trade: "inspect plug / fitting" },
    { home: "flange", trade: "inspect flange / fitting" },
    { home: "gasket", trade: "inspect / replace gasket" },
    { home: "o-ring", trade: "inspect / replace O-ring" },
    { home: "washer", trade: "inspect / replace washer" },
    { home: "nut", trade: "inspect / tighten nut" },
    { home: "bolt", trade: "inspect / tighten bolt" },
    { home: "screw", trade: "inspect / tighten screw" },
    { home: "clip", trade: "inspect / replace clip" },
    { home: "clamp", trade: "inspect / tighten clamp" },
    { home: "hanger", trade: "inspect / secure hanger" },
    { home: "strap", trade: "inspect / secure strap" },
    { home: "bracket", trade: "inspect / secure bracket" },
    { home: "support", trade: "inspect / add support" },
    { home: "saddle", trade: "inspect saddle / fitting" },
    { home: "tap", trade: "inspect tap / connection" },
    { home: "service", trade: "inspect service connection" },
    { home: "curb stop", trade: "inspect curb stop" },
    { home: "corp stop", trade: "inspect corp stop" },
    { home: "meter stop", trade: "inspect meter stop" },
    { home: "meter yoke", trade: "inspect meter yoke" },
    { home: "meter box", trade: "inspect meter box" },
    { home: "meter pit", trade: "inspect meter pit" },
    { home: "meter vault", trade: "inspect meter vault" },
    { home: "water service", trade: "inspect water service line" },
    { home: "sewer service", trade: "inspect sewer service line" },
    { home: "lateral", trade: "inspect lateral line" },
    { home: "main", trade: "inspect main line" },
    { home: "branch", trade: "inspect branch line" },
    { home: "run", trade: "inspect pipe run" },
    { home: "loop", trade: "inspect loop" },
    { home: "circuit", trade: "inspect circuit" },
    { home: "zone", trade: "inspect zone" },
    { home: "manifold", trade: "inspect manifold" },
    { home: "header", trade: "inspect header" },
    { home: "trunk", trade: "inspect trunk line" },
    { home: "riser", trade: "inspect riser" },
    { home: "drop", trade: "inspect drop" },
    { home: "feed", trade: "inspect feed line" },
    { home: "return", trade: "inspect return line" },
    { home: "supply", trade: "inspect supply line" },
    { home: "waste", trade: "inspect waste line" },
    { home: "vent", trade: "inspect vent" },
    { home: "soil", trade: "inspect soil pipe" },
    { home: "storm", trade: "inspect storm drain" },
    { home: "sanitary", trade: "inspect sanitary drain" },
    { home: "combined", trade: "inspect combined drain" },
    { home: "separate", trade: "inspect separate system" },
    { home: "septic", trade: "inspect septic system" },
    { home: "cesspool", trade: "inspect cesspool" },
    { home: "leach field", trade: "inspect leach field" },
    { home: "drain field", trade: "inspect drain field" },
    { home: "distribution box", trade: "inspect distribution box" },
    { home: "pump tank", trade: "inspect pump tank" },
    { home: "alarm", trade: "test alarm" },
    { home: "control panel", trade: "inspect control panel" },
    { home: "float", trade: "inspect float switch" },
    { home: "effluent filter", trade: "clean / replace effluent filter" },
    { home: "baffle", trade: "inspect baffle" },
    { home: "inlet", trade: "inspect inlet" },
    { home: "outlet", trade: "inspect outlet" },
    { home: "tee", trade: "inspect tee" },
    { home: "riser", trade: "inspect riser" },
    { home: "lid", trade: "inspect lid / access" },
    { home: "manhole", trade: "inspect manhole" },
    { home: "cleanout", trade: "inspect cleanout" },
    { home: "access", trade: "inspect access point" },
    { home: "cover", trade: "inspect cover" },
    { home: "extension", trade: "inspect extension" },
    { home: "adapter", trade: "inspect adapter" },
    { home: "coupler", trade: "inspect coupler" },
    { home: "repair coupling", trade: "inspect repair coupling" },
    { home: "no-hub coupling", trade: "inspect no-hub coupling" },
    { home: "hub coupling", trade: "inspect hub coupling" },
    { home: "shielded coupling", trade: "inspect shielded coupling" },
    { home: "transition coupling", trade: "inspect transition coupling" },
    { home: "mission coupling", trade: "inspect mission coupling" },
    { home: "fernco", trade: "inspect Fernco coupling" },
    { home: "donut", trade: "inspect donut gasket" },
    { home: "wax ring", trade: "replace wax ring" },
    { home: "waxless ring", trade: "replace waxless ring" },
    { home: "gasket", trade: "replace gasket" },
    { home: "seal", trade: "replace seal" },
    { home: "caulk", trade: "re-caulk" },
    { home: "sealant", trade: "apply sealant" },
    { home: "putty", trade: "apply plumber's putty" },
    { home: "tape", trade: "apply PTFE tape" },
    { home: "dope", trade: "apply pipe dope" },
    { home: "flux", trade: "apply flux" },
    { home: "solder", trade: "solder joint" },
    { home: "sweat", trade: "sweat joint" },
    { home: "braze", trade: "braze joint" },
    { home: "weld", trade: "weld joint" },
    { home: "thread", trade: "inspect thread / seal" },
    { home: "nipple", trade: "inspect nipple" },
    { home: "close nipple", trade: "inspect close nipple" },
    { home: "pipe nipple", trade: "inspect pipe nipple" },
    { home: "barb", trade: "inspect barb fitting" },
    { home: "push-fit", trade: "inspect push-fit fitting" },
    { home: "sharkbite", trade: "inspect SharkBite fitting" },
    { home: "quick-connect", trade: "inspect quick-connect fitting" },
    { home: "compression", trade: "inspect compression fitting" },
    { home: "flare", trade: "inspect flare fitting" },
    { home: "flare nut", trade: "inspect flare nut" },
    { home: "flare washer", trade: "inspect flare washer" },
    { home: "flare fitting", trade: "inspect flare fitting" },
    { home: "flare union", trade: "inspect flare union" },
    { home: "flare tee", trade: "inspect flare tee" },
    { home: "flare elbow", trade: "inspect flare elbow" },
    { home: "flare adapter", trade: "inspect flare adapter" },
    { home: "flare plug", trade: "inspect flare plug" },
    { home: "flare cap", trade: "inspect flare cap" },
    { home: "flare bushing", trade: "inspect flare bushing" },
    { home: "flare reducer", trade: "inspect flare reducer" },
    { home: "flare coupling", trade: "inspect flare coupling" },
  ],
